#!/usr/bin/env python3
"""
gen_chirp_mem.py — Generate the 11 chirp .mem files for the AERIS-10 FPGA.

3-ladder waveform set (chirp-v2 PR-B). Replaces the legacy 2-waveform script.
The legacy 6-file output (long_chirp_seg{0,1}_{i,q}.mem, short_chirp_{i,q}.mem,
long_chirp_lut.mem) is no longer regenerated by this script; the legacy files
on disk are deleted in PR-C (RX) and PR-E (TX) when their consumers go away.

TX side (DAC LUTs, 8-bit unsigned offset-binary, fs_dac = 120 MHz):
  tx_short_lut.mem    120  samples (1 µs)
  tx_medium_lut.mem   600  samples (5 µs)
  tx_long_lut.mem     3600 samples (30 µs)

RX side (matched-filter reference, Q15 I/Q hex, fs_sys = 100 MHz, all 2048 entries):
  rx_short_i.mem  / rx_short_q.mem    100  active + 1948 zero-pad
  rx_medium_i.mem / rx_medium_q.mem   500  active + 1548 zero-pad
  rx_long_seg0_i.mem / rx_long_seg0_q.mem   2048 (samples 0..2047 of long chirp)
  rx_long_seg1_i.mem / rx_long_seg1_q.mem   952 active + 1096 zero-pad
                                             (samples 2048..2999 of long chirp)

Phase model (baseband, post-DDC for RX, pre-upmix for TX):
  phase(n)   = 2π · F_BASEBAND_LOW · t + π · chirp_rate · t²
  chirp_rate = CHIRP_BW / T_chirp
  F_BASEBAND_LOW = 10 MHz
  CHIRP_BW       = 20 MHz   (uniform across all three waveforms — same range res)

End-to-end frequency plan (TX-I, unchanged from chirp-v1):
  DAC LUT  : 10..30 MHz @ fs_dac=120 MHz
  TX upmix : LO=10.500 GHz, high-side -> RF transmitted: 10.510..10.530 GHz
  RX downmix: LO=10.380 GHz, high-side -> IF at ADC:    130..150 MHz
  DDC NCO  : 120 MHz exactly (ddc_400m.v) -> baseband:   10..30 MHz

radar_scene.py uses the same F_BASEBAND_LOW and CHIRP_BW constants; both
must stay in sync.

Scaling: 0.9 of full-scale for the Q15 (RX) path. TX LUT scales 127·0.9 ≈ 114
into the ±127 swing around the 128 (8'd128) idle code.

Usage:
    python3 gen_chirp_mem.py
"""

import math
import os
import sys

# ============================================================================
# AERIS-10 Parameters
# ============================================================================
CHIRP_BW = 20e6                 # 20 MHz sweep — same for all three waveforms
FS_SYS   = 100e6                # System clock for RX matched filter
FS_DAC   = 120e6                # DAC clock for TX waveform synthesis
F_BASEBAND_LOW = 10e6           # Low edge of post-DDC baseband
SCALE = 0.9                     # Backoff from full-scale (both paths)

# Waveform durations (seconds) — see radar_params.vh RP_DEF_*_CHIRP_CYCLES_V2
T_SHORT  = 1e-6                 # 1 µs   (PR-B v2; chirp-v1 was 0.5 µs)
T_MEDIUM = 5e-6                 # 5 µs
T_LONG   = 30e-6                # 30 µs

# RX FFT segment size — chirp_reference_rom (PR-C) uses one 2048-entry BRAM
# per waveform lane. LONG is the only waveform that crosses the segment
# boundary; SHORT and MEDIUM fit in a single 2048-entry buffer with zero-pad.
FFT_SIZE = 2048

# Q15 / 8-bit envelopes
Q15_MAX  = 32767
DAC_MID  = 128                  # 8'd128 idle code (offset-binary)
DAC_AMP  = 127                  # ±127 swing around DAC_MID

# Output directory: FPGA RTL root (.mem files live alongside the .v files)
MEM_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')


# ============================================================================
# Sample generation — single phase model reused for both TX and RX
# ============================================================================
def chirp_phase(n: int, fs: float, t_chirp: float) -> float:
    """Phase at sample n for the LFM upchirp."""
    chirp_rate = CHIRP_BW / t_chirp
    t = n / fs
    return 2 * math.pi * F_BASEBAND_LOW * t + math.pi * chirp_rate * t * t


def gen_rx_iq(t_chirp: float):
    """Generate Q15 I/Q samples at fs_sys for one chirp duration."""
    n_samples = round(t_chirp * FS_SYS)
    chirp_i, chirp_q = [], []
    for n in range(n_samples):
        ph = chirp_phase(n, FS_SYS, t_chirp)
        re = max(-32768, min(32767, round(Q15_MAX * SCALE * math.cos(ph))))
        im = max(-32768, min(32767, round(Q15_MAX * SCALE * math.sin(ph))))
        chirp_i.append(re)
        chirp_q.append(im)
    return chirp_i, chirp_q


def gen_tx_real(t_chirp: float):
    """Generate 8-bit unsigned offset-binary real samples at fs_dac."""
    n_samples = round(t_chirp * FS_DAC)
    samples = []
    for n in range(n_samples):
        ph = chirp_phase(n, FS_DAC, t_chirp)
        # Real-valued upchirp: cos(phase). Map ±1 → 0..255 with 128 as DC.
        v = round(DAC_AMP * SCALE * math.cos(ph)) + DAC_MID
        samples.append(max(0, min(255, v)))
    return samples


# ============================================================================
# .mem writers
# ============================================================================
def to_hex_signed16(value: int) -> str:
    """Signed 16-bit → 4-char hex (two's complement, lowercase)."""
    if value < 0:
        value += 0x10000
    return f"{value:04x}"


def to_hex_u8(value: int) -> str:
    """Unsigned 8-bit → 2-char hex (uppercase, matches legacy long_chirp_lut.mem)."""
    return f"{value:02X}"


def write_lines(filename: str, lines):
    path = os.path.join(MEM_DIR, filename)
    with open(path, 'w') as f:
        for line in lines:
            f.write(line + '\n')
    return path


def write_rx_iq_padded(prefix: str, chirp_i, chirp_q, target_len: int = FFT_SIZE,
                       offset: int = 0):
    """
    Write {prefix}_i.mem and {prefix}_q.mem with `target_len` lines.
    `offset` selects which slice of the chirp to write — used for LONG segmentation.
    Cells past the chirp end are zero-padded. Cells before the chirp start (impossible
    here but kept symmetric) are also zero.
    """
    i_lines, q_lines = [], []
    for k in range(target_len):
        src_idx = k + offset
        if 0 <= src_idx < len(chirp_i):
            i_lines.append(to_hex_signed16(chirp_i[src_idx]))
            q_lines.append(to_hex_signed16(chirp_q[src_idx]))
        else:
            i_lines.append('0000')
            q_lines.append('0000')
    write_lines(f"{prefix}_i.mem", i_lines)
    write_lines(f"{prefix}_q.mem", q_lines)


def write_tx_lut(filename: str, samples):
    """Write 8-bit TX LUT — one sample per line, exactly len(samples) lines."""
    write_lines(filename, [to_hex_u8(v) for v in samples])


# ============================================================================
# main
# ============================================================================
def verify_phase_match():
    """
    Cross-check that each generated chirp matches the closed-form phase model
    bit-exactly. radar_scene.py uses the same phase formula and constants;
    if it ever diverges, this assertion will fire.
    """
    for name, t_chirp in [("SHORT", T_SHORT), ("MEDIUM", T_MEDIUM), ("LONG", T_LONG)]:
        i, q = gen_rx_iq(t_chirp)
        n_check = min(64, len(i))
        for n in range(n_check):
            ph = chirp_phase(n, FS_SYS, t_chirp)
            ei = max(-32768, min(32767, round(Q15_MAX * SCALE * math.cos(ph))))
            eq = max(-32768, min(32767, round(Q15_MAX * SCALE * math.sin(ph))))
            assert i[n] == ei and q[n] == eq, f"{name} phase mismatch at n={n}"


def main():
    verify_phase_match()

    # ---- TX LUTs (8-bit real, fs_dac = 120 MHz) ----
    write_tx_lut("tx_short_lut.mem",  gen_tx_real(T_SHORT))    # 120 lines
    write_tx_lut("tx_medium_lut.mem", gen_tx_real(T_MEDIUM))   # 600 lines
    write_tx_lut("tx_long_lut.mem",   gen_tx_real(T_LONG))     # 3600 lines

    # ---- RX I/Q (Q15, fs_sys = 100 MHz, all padded to FFT_SIZE=2048) ----
    short_i, short_q   = gen_rx_iq(T_SHORT)    # 100 active samples
    medium_i, medium_q = gen_rx_iq(T_MEDIUM)   # 500 active samples
    long_i, long_q     = gen_rx_iq(T_LONG)     # 3000 active samples

    write_rx_iq_padded("rx_short",  short_i,  short_q)              # offset=0
    write_rx_iq_padded("rx_medium", medium_i, medium_q)             # offset=0
    write_rx_iq_padded("rx_long_seg0", long_i, long_q, offset=0)              # [0..2047]
    write_rx_iq_padded("rx_long_seg1", long_i, long_q, offset=FFT_SIZE)       # [2048..2999]+pad

    return 0


if __name__ == '__main__':
    sys.exit(main())
